# Generated by Django 3.1.14 on 2022-04-13 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_software_technical'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Software',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='technical',
            name='level',
        ),
        migrations.RemoveField(
            model_name='technical',
            name='percentage',
        ),
    ]
