# Generated by Django 3.1.14 on 2022-04-13 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220413_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='job',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subimage',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subtitle',
        ),
    ]
