# Generated by Django 3.1.14 on 2022-04-14 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220413_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='heroku',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='heroku_url'),
        ),
    ]
